# Generated by Django 5.0.4 on 2024-04-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodct',
            new_name='Product',
        ),
    ]
